import { transporter } from './mailTransporter';

export async function sendReportEmail(
  to: string,
  username: string,
  attachment: Buffer,
  filename: string,
  type: 'PDF' | 'EXCEL'
): Promise<void> {
  // Validate SMTP configuration first
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS || 
      process.env.SMTP_USER === 'your_gmail_address@gmail.com') {
    throw new Error('SMTP credentials are not configured. Please set SMTP_USER and SMTP_PASS in your .env.local file.');
  }

  const htmlBody = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 0 auto; background: #f8f9fa; padding: 32px 16px;">
      <div style="background: #3741c8; border-radius: 8px; padding: 28px 32px; margin-bottom: 24px;">
        <h1 style="margin: 0; font-size: 20px; font-weight: 700; color: #ffffff;">Finance Dashboard</h1>
        <p style="margin: 6px 0 0; color: rgba(255,255,255,0.8); font-size: 13px;">Financial Report Delivery</p>
      </div>
      <div style="background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 28px 32px; margin-bottom: 24px;">
        <p style="margin: 0 0 12px; font-size: 15px; color: #111827;">Hi <strong>${username}</strong>,</p>
        <p style="margin: 0 0 24px; font-size: 14px; color: #6b7280; line-height: 1.6;">
          Your requested ${type} financial report is attached to this email. You can view your professional transaction history and financial summary.
        </p>
        <div style="background: #f3f4f6; border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 24px;">
          <p style="margin: 0; font-size: 14px; color: #3741c8; font-weight: 600;">File: ${filename}</p>
        </div>
        <p style="margin: 0; font-size: 14px; color: #6b7280; line-height: 1.6;">
          If you didn't request this report, please ignore this email or check your dashboard security settings.
        </p>
      </div>
      <div style="text-align: center; padding: 0 20px;">
        <p style="margin: 0 0 8px; font-size: 12px; color: #9ca3af;">
          Generated by Finance Dashboard Pro
        </p>
        <p style="margin: 0; font-size: 11px; color: #d1d5db;">
          This is an automated email. Please do not reply.
        </p>
      </div>
    </div>
  `;

  await transporter.sendMail({
    from: `"Finance Dashboard" <${process.env.SMTP_USER}>`,
    to,
    subject: `Your Financial Report: ${filename}`,
    html: htmlBody,
    attachments: [
      {
        filename,
        content: attachment,
      },
    ],
  });
}
